
name: Checks
on:
  push:
    branches: [main]
  pull_request:

env:
  PYTEST_ADDOPTS: --color=yes
  PIP_PROGRESS_BAR: "off"

jobs:

  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check code is formatted (Black)
        uses: psf/black@stable
        with:
          options: "--check"
          version: "~= 22.0"

  pytest:
    name: pytest (${{ matrix.os }}/${{ matrix.python-version }}/${{ matrix.install-mode }})
    runs-on: ${{ matrix.os-version }}
    needs: [code-formatting]
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          # keep additional Python versions commented while private to reduce number of jobs
          # (CI jobs run in private repos are counted towards monthly usage limits for the entire org)
          # - "3.9"
          # - "3.10"
          - "3.11"
        os:
          - linux
          - win64
        install-mode:
          - editable
          - noneditable
        include:
          - os: linux
            os-version: ubuntu-latest
          - os: win64
            os-version: windows-latest
    steps:
      - uses: actions/checkout@v4
        if: matrix.install-mode == 'editable'
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install (editable)
        if: matrix.install-mode == 'editable'
        run: |
          pip install -r requirements-dev.txt
      - name: Install (noneditable)
        if: matrix.install-mode == 'noneditable'
        run: |
          pip install "git+${{ format('{0}/{1}@{2}', github.server_url, github.repository, github.ref) }}"
      - name: Set up IDAES solvers
        run: |
          idaes get-extensions --verbose
      - name: Run pytest
        run: |
         pip install pytest  # ensure pytest is installed (should do nothing if already present from requirements-dev.txt
          pytest --pyargs watertap_contrib.rENRTL
